name: Build docker image & publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/K-4U/ha-keepalive:latest
        docker run ghcr.io/K-4U/ha-keepalive:latest
        docker push ghcr.io/K-4U/ha-keepalive:latest
        
      
